This script processes supplements from [Dweck et al. 2018](https://www.cell.com/cell-reports/abstract/S2211-1247(18)30663-6): 
- Mapping between chemical to receptors are in firing rates (normalised); whereas fruit to receptors are in 'number of responses' (not normalised). 
- There are times when there are multiple receptors in the same columns. In that case those columns are duplicated, and unique names are given. 
- And there are times when multiple receptors map to the same glomerulus in the adult. In that case the max is taken: for one odour, if one receptor responds, then the ORNs in that glomerulus respond.

It saves: 
- adult_chem2glom.csv 
- larva_chem2or.csv 
- adult_fruit2glom.csv 
- larva_fruit2or.csv

In [1]:
import pandas as pd
import numpy as np

# pre-processed DoOR data

In [2]:
# preprocessed DoOR data 
door = pd.read_csv('data/DoOR/processed_door_adult.csv')
door

,glomerulus,sfr_SFR,water_XLYOFNOQVPJJNP-UHFFFAOYSA-N,ammonium hydroxide_VHUUQVKOLVNVRT-UHFFFAOYSA-N,putrescine_KIDHWZJUCRJVML-UHFFFAOYSA-N,cadaverine_VHRGRCVQAFMJIZ-UHFFFAOYSA-N,ammonia_QGZKDVFQNNGYKY-UHFFFAOYSA-N,ethanolamine_HZAXFHJVJLSVMW-UHFFFAOYSA-N,heptylamine_WJYIASZWHGOTOU-UHFFFAOYSA-N,isoamylamine_BMFVGAAISNGQNM-UHFFFAOYSA-N,...,(Z)-7-tricosene_IRYCVIRCWSSJOW-SQFISAMPSA-N,(Z)-9-tricosene_IGOWHGRNPLFNDJ-ZPHPHTNESA-N,(Z)-7-pentacosene_RORWYUWDGGVNRJ-SQFISAMPSA-N,"(Z,Z)-7,11-pentacosadiene_PJVWXEURPGIPNW-ADYYPQGGSA-N","(Z,Z)-7,11-heptacosadiene_RJYQFYALHBHYMG-ADYYPQGGSA-N","(Z,Z)-7,11-octacosadiene_KJSVCIRMHUQNGQ-ADYYPQGGSA-N","(Z,Z)-7,11-nonacosadiene_KWUWRILZYFCPRI-ADYYPQGGSA-N",methyl laurate_UQDUPQYQJKYHQI-UHFFFAOYSA-N,methyl palmitate_FLIACVVOZYBSBS-UHFFFAOYSA-N,palmitoleic acid_SECPZKHBENQXJG-FPLPWBNLSA-N
0,D,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,DA1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,DA2,0.064859,0.017059,0.000000,0.306816,0.025091,0.305932,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,DA3,0.019317,0.000000,0.015024,0.015024,0.004293,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,DA4l,0.095284,0.000000,0.090697,0.032186,0.048279,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,DA4m,0.048452,0.000000,0.056635,0.063791,0.051927,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,DC1,0.100069,0.000000,0.097216,0.080654,0.085971,0.000000,0.000000,0.037799,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,DC2,0.079803,0.197693,0.123406,0.153453,0.000000,0.118779,0.128289,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,DC3,0.078341,0.000000,0.000000,0.000000,0.000000,0.170507,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,DC4,0.000000,0.854963,0.028357,0.326230,0.293186,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,DL1,0.051661,0.056733,0.053919,0.056745,0.046383,0.098206,0.076186,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,DL2d,0.096468,0.222510,0.210477,0.189889,0.165465,0.069736,0.119537,0.045201,0.048257,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,DL2v,0.096468,0.222510,0.210477,0.189889,0.165465,0.069736,0.119537,0.045201,0.048257,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,DL3,0.059483,0.000000,0.069288,0.052747,0.056136,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,DL4,0.033910,0.011961,0.086625,0.060990,0.083885,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,DL5,0.025324,0.094439,0.067536,0.050442,0.018918,0.083416,0.085440,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,DM1,0.051595,0.224558,0.112581,0.258615,0.000000,0.031245,0.031245,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,DM2,0.084485,0.367991,0.184984,0.175114,0.089895,0.088053,0.281272,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,DM3,0.062801,0.092289,0.081420,0.122185,0.023729,0.100839,0.128126,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,DM4,0.023728,0.042720,0.011539,0.029669,0.027600,0.012522,0.015449,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,DM5,0.062801,0.007993,0.033180,0.024214,0.024449,0.004805,0.028675,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,DM6,0.024548,0.000000,0.041547,0.007164,0.002388,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,DP1l,0.171429,0.304460,0.175510,0.913265,0.686735,0.000000,0.220408,0.002041,0.001020,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,DP1m,0.015990,0.180955,0.021453,0.147709,0.101904,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,V,0.141139,0.000000,0.000000,0.000000,0.000000,0.171432,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,VA1d,0.056317,0.000000,0.056250,0.043821,0.056250,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,VA1v,0.197855,0.000000,0.177528,0.133133,0.157656,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,VA2,0.034113,0.024357,0.010899,0.017217,0.000000,0.019872,0.019872,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,VA3,0.050915,0.116168,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,VA4,0.047167,0.093545,0.044821,0.081549,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,VA5,0.048048,0.079108,0.056105,0.064126,0.055188,0.077990,0.077990,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,VA6,0.026609,0.061801,0.030076,0.047113,0.020635,0.050246,0.050246,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,VA7l,0.098147,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,VC1,0.045616,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,VC2,0.030487,0.021248,0.021674,0.036206,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,VC3,0.096468,0.156807,0.378349,0.412169,0.099708,0.109468,0.119537,0.453448,0.362477,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,VC4,0.022870,0.025775,0.025907,0.042122,0.038883,0.070999,0.070999,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,VC5,0.171429,0.328675,0.175510,0.913265,0.686735,0.000000,0.220408,0.002041,0.001020,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,VL1,0.186086,0.266665,0.698276,0.913265,0.686735,0.000000,0.415533,0.139113,0.109303,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,VL2a,0.174646,0.201460,0.004327,0.162411,0.166272,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,VL2p,0.186086,0.257240,0.698276,0.243900,0.422760,0.000000,0.415533,0.139113,0.109303,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,VM1,0.186086,0.257240,0.698276,0.243900,0.422760,0.000000,0.415533,0.139113,0.109303,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42,VM2,0.014896,0.065393,0.019648,0.049264,0.053182,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,VM3,0.064345,0.068775,0.108420,0.097870,0.139903,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44,VM4,0.044802,0.033877,0.057867,0.028581,0.034487,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45,VM5d,0.064954,0.219674,0.054040,0.167341,0.101271,0.298913,0.191017,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46,VM5v,0.015172,0.148023,0.068181,0.072719,0.078750,0.099895,0.099895,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47,VM7d,0.082041,0.122896,0.031018,0.174700,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48,VM7v,0.035801,0.036854,0.034775,0.064401,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
receptor2glom = pd.read_csv(
    'data/DoOR/door_receptor_mappings.csv', index_col=0)
receptor2glom

,receptor,sensillum,OSN,glomerulus,co.receptor,coexpressing,related1,related2,related3,related4,related5,related6,Ors,sensillum.type,adult,larva,dataset.existing,comment,code,code.OSN
1,?,?,?,VA7m,?,NaN,NaN,NaN,NaN,NaN,NaN,NaN,?,NaN,NaN,NaN,False,NaN,VA7m,NaN
2,Or42b,ab1,ab1A,DM1,Orco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Or42b,antennal basiconic,True,True,True,NaN,DM1,ab1A
3,Or92a,ab1,ab1B,VA2,Orco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Or92a,antennal basiconic,True,NaN,True,NaN,VA2,ab1B
4,Gr21a.Gr63a,ab1,ab1C,V,NaN,Gr21a+Gr63a,NaN,NaN,NaN,NaN,NaN,NaN,Gr21a+Gr63a,antennal basiconic,True,True,True,NaN,V,ab1C
5,Or10a,ab1,ab1D,DL1,Orco,Gr10a,Gr10a,NaN,NaN,NaN,NaN,NaN,Or10a+Gr10a,antennal basiconic,True,NaN,True,NaN,DL1,ab1D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,Or83a,NaN,NaN,NaN,Orco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True,True,NaN,NaN,NaN
93,Or83b,NaN,NaN,NaN,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,False,the Orco co-receptor expressed together with a...,NaN,NaN
94,Or85c,NaN,NaN,NaN,Orco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True,True,NaN,NaN,NaN
95,Or94a,NaN,NaN,NaN,Orco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True,True,NaN,NaN,NaN
96,Or94b,NaN,NaN,NaN,Orco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,True,True,NaN,NaN,NaN

In [4]:
door_chemical_meta = pd.read_csv(
    'data/DoOR/door_chemical_meta.csv', index_col=0)
door_chemical_meta

,Class,Name,InChIKey,CID,CAS,Stensmyr.2003.WT,Schmuker.2007.TR,Dobritsa.2003.WT,Bruyne.2001.WT,Bruyne.2010.WT,Marshall.2010.WT,Hallem.2004.WT
1,NaN,sfr,SFR,SFR,SFR,NaN,1.0,NaN,1.0,0.0,0.000,NaN
2,other,water,XLYOFNOQVPJJNP-UHFFFAOYSA-N,962,7732-18-5,NaN,NaN,NaN,NaN,NaN,5.714,NaN
3,amine,ammonium hydroxide,VHUUQVKOLVNVRT-UHFFFAOYSA-N,14923,1336-21-6,NaN,NaN,NaN,NaN,NaN,2.714,NaN
4,amine,putrescine,KIDHWZJUCRJVML-UHFFFAOYSA-N,1045,110-60-1,NaN,0.0,NaN,NaN,NaN,5.667,NaN
5,amine,cadaverine,VHRGRCVQAFMJIZ-UHFFFAOYSA-N,273,462-94-2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
689,NaN,"(Z,Z)-7,11-octacosadiene",KJSVCIRMHUQNGQ-ADYYPQGGSA-N,14464905,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
690,NaN,"(Z,Z)-7,11-nonacosadiene",KWUWRILZYFCPRI-ADYYPQGGSA-N,14367348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
691,NaN,methyl laurate,UQDUPQYQJKYHQI-UHFFFAOYSA-N,8139,111-82-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
692,NaN,methyl palmitate,FLIACVVOZYBSBS-UHFFFAOYSA-N,8181,112-39-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
693,NaN,palmitoleic acid,SECPZKHBENQXJG-FPLPWBNLSA-N,445638,373-49-9,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Dweck 2018 data

### supp2  chemical-OR
Table S1. List of identified active compounds in both larval and adult Drosophila (related to Fig. 2)  
Numbers represent  maximum frequency (Hz) responses (mean ± SD) to  10-4 concentration of synthetic standards of the active copmpounds (n = 2-3recordings). Synthetic standards were applied via GC in GC-SSR experiments, which accounts for the very accurate stimulus delivery and the corresponding low standard deviations.

In [5]:
chem2or = pd.read_excel('data/Dweck2018/1-s2.0-S2211124718306636-mmc2.xlsx', 
                      skiprows=7)
chem2or.rename(columns={'Unnamed: 0': 'chemical'}, inplace=True)

# there are columns where the entire column is filled with NaNs. 
# I'll take this to mean that authors tried this receptor, but it didn't respond to any chemicals 
# therefore we will keep them, and replace all NaNs with 0. 
# and remove empty strings 
chem2or.replace({' ': np.nan}, inplace=True)

chem2or

,chemical,CAS number,Or2a,Or7a,Or9a,Or10a,Or13a,Or19a,Or22a/Or22b,Or22c,...,Or83c,Or85a,Or85b,Or85c,Or85d,Or88a,Or92a,Or94a,Or94b,Or98a
0,(-)-(E)-Caryophyllene,87-44-5,NaN,NaN,NaN,NaN,NaN,71 ±4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(-)-a-Copaene,3856-25-5,NaN,NaN,NaN,NaN,NaN,62 ± 2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(-)-Camphor,464-48-2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(-)-Menthone,14073-97-3,NaN,NaN,NaN,NaN,NaN,60 ± 0.4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(-)-Terpinen-4-ol,20126-76-5,NaN,NaN,NaN,NaN,NaN,42 ± 1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,Veratrole,91-16-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,187 ± 12,NaN,NaN
112,β-Citronellol,106-22-9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,β-Elemene,33880-83-0,NaN,NaN,NaN,NaN,NaN,43 ± 3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,β-Ionone,79-77-6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,β-Myrcene,123-35-3,NaN,NaN,NaN,NaN,NaN,20 ± 0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# tidy up the numbers: take the mean only 
for col in chem2or.columns:
    if col not in ['chemical','CAS number']:
        vs = []
        for v in chem2or[col]: 
            if pd.isna(v): 
                vs.append(np.nan)
            elif type(v) == int: 
                vs.append(int(v))
            elif (type(v) == np.float64) or (type(v) == float): 
                vs.append(int(v))
            else: 
                vs.append(int(v.split(' ±')[0]))
        chem2or[col] = vs
chem2or

,chemical,CAS number,Or2a,Or7a,Or9a,Or10a,Or13a,Or19a,Or22a/Or22b,Or22c,...,Or83c,Or85a,Or85b,Or85c,Or85d,Or88a,Or92a,Or94a,Or94b,Or98a
0,(-)-(E)-Caryophyllene,87-44-5,NaN,NaN,NaN,NaN,NaN,71.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(-)-a-Copaene,3856-25-5,NaN,NaN,NaN,NaN,NaN,62.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(-)-Camphor,464-48-2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(-)-Menthone,14073-97-3,NaN,NaN,NaN,NaN,NaN,60.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(-)-Terpinen-4-ol,20126-76-5,NaN,NaN,NaN,NaN,NaN,42.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,Veratrole,91-16-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,187.0,NaN,NaN
112,β-Citronellol,106-22-9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,β-Elemene,33880-83-0,NaN,NaN,NaN,NaN,NaN,43.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,β-Ionone,79-77-6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,β-Myrcene,123-35-3,NaN,NaN,NaN,NaN,NaN,20.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
chem2or.columns.unique()

Index(['chemical', 'CAS number', 'Or2a', 'Or7a', 'Or9a', 'Or10a', 'Or13a',
       'Or19a', 'Or22a/Or22b', 'Or22c', 'Or23a', 'Or24a', 'Or30a', 'Or33b',
       'Or33c/Or85e', 'Or35a', 'Or42a', 'Or42b', 'Or43a', 'Or43b', 'Or45a',
       'Or45b', 'Or46a', 'Or47a', 'Or47b', 'Or49a/Or85f', 'Or49b', 'Or56a',
       'Or59a', 'Or59b', 'Or59c', 'Or65a', 'Or67a', 'Or67b', 'Or67c', 'Or67d',
       'Or69a', 'Or71a', 'Or74a', 'Or82a', 'Or83c', 'Or85a', 'Or85b', 'Or85c',
       'Or85d', 'Or88a', 'Or92a', 'Or94a', 'Or94b', 'Or98a'],
      dtype='object')

In [8]:
# multiple receptors are mixed into the same column, which means they can't be directly mapped to glomerulus. 
# let's duplicate those columns 
chem2or.loc[:,['Or22b']] = chem2or['Or22a/Or22b'].copy()
chem2or.loc[:, ['Or85e']] = chem2or['Or33c/Or85e'].copy()
chem2or.rename(columns={
    'Or22a/Or22b': 'Or22a', 
    'Or33c/Or85e': 'Or33c'
}, inplace=True)
chem2or.fillna(0, inplace = True)

chem2or

,chemical,CAS number,Or2a,Or7a,Or9a,Or10a,Or13a,Or19a,Or22a,Or22c,...,Or85b,Or85c,Or85d,Or88a,Or92a,Or94a,Or94b,Or98a,Or22b,Or85e
0,(-)-(E)-Caryophyllene,87-44-5,0.0,0.0,0.0,0.0,0.0,71.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,(-)-a-Copaene,3856-25-5,0.0,0.0,0.0,0.0,0.0,62.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,(-)-Camphor,464-48-2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39.0
3,(-)-Menthone,14073-97-3,0.0,0.0,0.0,0.0,0.0,60.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,(-)-Terpinen-4-ol,20126-76-5,0.0,0.0,0.0,0.0,0.0,42.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,Veratrole,91-16-7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,187.0,0.0,0.0,0.0,0.0
112,β-Citronellol,106-22-9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
113,β-Elemene,33880-83-0,0.0,0.0,0.0,0.0,0.0,43.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
114,β-Ionone,79-77-6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,51.0
115,β-Myrcene,123-35-3,0.0,0.0,0.0,0.0,0.0,20.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
# to normalise, dividing by the max of all receptors 
# assuming that receptors are more or less similar, 
# and that odours are not super complete to reach the whole range for all receptors 
chem2or_values = chem2or.set_index(['chemical','CAS number'])
chem2or_values = chem2or_values / chem2or_values.max().max()
chem2or = chem2or_values.reset_index()
chem2or

,chemical,CAS number,Or2a,Or7a,Or9a,Or10a,Or13a,Or19a,Or22a,Or22c,...,Or85b,Or85c,Or85d,Or88a,Or92a,Or94a,Or94b,Or98a,Or22b,Or85e
0,(-)-(E)-Caryophyllene,87-44-5,0.0,0.0,0.0,0.0,0.0,0.331776,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
1,(-)-a-Copaene,3856-25-5,0.0,0.0,0.0,0.0,0.0,0.289720,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
2,(-)-Camphor,464-48-2,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.182243
3,(-)-Menthone,14073-97-3,0.0,0.0,0.0,0.0,0.0,0.280374,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
4,(-)-Terpinen-4-ol,20126-76-5,0.0,0.0,0.0,0.0,0.0,0.196262,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,Veratrole,91-16-7,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.873832,0.0,0.0,0.0,0.000000
112,β-Citronellol,106-22-9,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
113,β-Elemene,33880-83-0,0.0,0.0,0.0,0.0,0.0,0.200935,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
114,β-Ionone,79-77-6,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.238318
115,β-Myrcene,123-35-3,0.0,0.0,0.0,0.0,0.0,0.093458,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000

In [10]:
# map chemicals to adult glomeruli 
receptor_to_glom = dict(zip(receptor2glom.receptor[~receptor2glom.glomerulus.isna()], 
receptor2glom.glomerulus[~receptor2glom.glomerulus.isna()]))

adult_chem2or = pd.concat([chem2or[['chemical','CAS number']], 
# only get the receptors that can be mapped to the glomerulus according to Munch and Galizia 
chem2or.loc[:,chem2or.columns.isin(receptor_to_glom)]], axis = 1)
adult_chem2or.columns = [receptor_to_glom[r] if r in receptor_to_glom else r for r in adult_chem2or.columns] 

adult_chem2or.columns

Index(['chemical', 'CAS number', 'DA4m', 'DL5', 'VM3', 'DL1', 'DC2', 'DC1',
       'DM2', 'DA3', 'DM5+DM3', 'VC1', 'VC3', 'VM7d', 'DM1', 'DA4l', 'VM2',
       'VA7l', 'DM3', 'VA1v', 'VA5', 'DA2', 'DM4', 'VM7v', 'DL3', 'DM6', 'VA3',
       'VC4', 'DA1', 'D', 'VC2', 'VA6', 'DC3', 'DM5', 'VM5d', 'VA4', 'VA1d',
       'VA2', 'VM5v', 'DM2', 'VC1'],
      dtype='object')

In [11]:
# DM3 and DM5 appearing multiple times 
# glomeruli map back to the receptors. So e.g. DM3 has multiple receptors. 
# DM3 ORNs activate when either receptor activates. Therefore we can take the max 
adult_chem2or.loc[:,'DM3'] = adult_chem2or[['DM3','DM5+DM3']].max(axis = 1)
adult_chem2or.loc[:,'DM5'] = adult_chem2or[['DM5','DM5+DM3']].max(axis = 1)
adult_chem2or.drop('DM5+DM3', axis = 1, inplace = True)

adult_chem2or

,chemical,CAS number,DA4m,DL5,VM3,DL1,DC2,DC1,DM2,DA3,...,VA6,DC3,DM5,VM5d,VA4,VA1d,VA2,VM5v,DM2,VC1
0,(-)-(E)-Caryophyllene,87-44-5,0.0,0.0,0.0,0.0,0.0,0.331776,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
1,(-)-a-Copaene,3856-25-5,0.0,0.0,0.0,0.0,0.0,0.289720,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
2,(-)-Camphor,464-48-2,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.182243
3,(-)-Menthone,14073-97-3,0.0,0.0,0.0,0.0,0.0,0.280374,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
4,(-)-Terpinen-4-ol,20126-76-5,0.0,0.0,0.0,0.0,0.0,0.196262,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,Veratrole,91-16-7,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
112,β-Citronellol,106-22-9,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
113,β-Elemene,33880-83-0,0.0,0.0,0.0,0.0,0.0,0.200935,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
114,β-Ionone,79-77-6,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.238318
115,β-Myrcene,123-35-3,0.0,0.0,0.0,0.0,0.0,0.093458,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000

In [12]:
#how many are shared with DoOR? 
len(set(adult_chem2or['CAS number']) & set(door_chemical_meta.CAS))

88

In [13]:
#which glomerulus is missing in Dweck et al. compared to DoOR? 
set(door.glomerulus) - set(adult_chem2or.columns)

{'DC4',
 'DL2d',
 'DL2v',
 'DL4',
 'DP1l',
 'DP1m',
 'V',
 'VC5',
 'VL1',
 'VL2a',
 'VL2p',
 'VM1',
 'VM4'}

In [14]:
# any present in Dweck but not DoOR? 
set(adult_chem2or.columns) - set(door.glomerulus)

{'CAS number', 'chemical'}

In [15]:
# further tidy up to have glomeruli in the rows 
adult_chem2or = adult_chem2or.drop('CAS number', axis = 1).set_index('chemical').T
adult_chem2or.index.name = 'glomerulus'
adult_chem2or

chemical,(-)-(E)-Caryophyllene,(-)-a-Copaene,(-)-Camphor,(-)-Menthone,(-)-Terpinen-4-ol,(+)-Limonene oxide,(±)-6-Methyl-5-hepten-2-ol,(±)-Ethyl 3-acetoxy butyrate,(±)-Sabinene,(E)-2-Hexen-1-yl propionate,...,Phenethyl isobutyrate,Phenethyl propionate,Prenyl acetate,Terpinolene,Valencene,Veratrole,β-Citronellol,β-Elemene,β-Ionone,β-Myrcene
glomerulus,,,,,,,,,,,,,,,,,,,,,
DA4m,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
DL5,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
VM3,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
DL1,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
DC2,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
DC1,0.331776,0.28972,0.000000,0.280374,0.196262,0.275701,0.000000,0.000000,0.163551,0.000000,...,0.000000,0.000000,0.098131,0.172897,0.21028,0.000000,0.00000,0.200935,0.000000,0.093458
DM2,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
DA3,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
VC1,0.000000,0.00000,0.182243,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.238318,0.000000
VC3,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.373832,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
VM7d,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
DM1,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
DA4l,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
VM2,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
VA7l,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
DM3,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
VA1v,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
VA5,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.836449,0.00000,0.000000,0.000000,0.000000
DA2,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
DM4,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
VM7v,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
DL3,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
DM6,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.266355,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
VA3,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.448598,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
VC4,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
DA1,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
D,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.149533,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.21028,0.000000,0.000000,0.000000
VC2,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
VA6,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
DC3,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
DM5,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.682243,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
VM5d,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
VA4,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.672897,0.766355,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
VA1d,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
VA2,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
VM5v,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.976636,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.901869,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
DM2,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000
VC1,0.000000,0.00000,0.182243,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.00000,0.000000,0.238318,0.000000

In [16]:
# larva
larva_chem2or = pd.concat([chem2or[['chemical','CAS number']], 
chem2or.loc[:, chem2or.columns.isin(receptor2glom.receptor[receptor2glom.larva.isin([True])])]], axis = 1)
larva_chem2or = larva_chem2or.drop('CAS number', axis = 1).set_index('chemical').T
larva_chem2or.index.name = 'receptor'
larva_chem2or

chemical,(-)-(E)-Caryophyllene,(-)-a-Copaene,(-)-Camphor,(-)-Menthone,(-)-Terpinen-4-ol,(+)-Limonene oxide,(±)-6-Methyl-5-hepten-2-ol,(±)-Ethyl 3-acetoxy butyrate,(±)-Sabinene,(E)-2-Hexen-1-yl propionate,...,Phenethyl isobutyrate,Phenethyl propionate,Prenyl acetate,Terpinolene,Valencene,Veratrole,β-Citronellol,β-Elemene,β-Ionone,β-Myrcene
receptor,,,,,,,,,,,,,,,,,,,,,
Or2a,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
Or7a,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
Or9a,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
Or22c,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
Or24a,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
Or30a,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
Or33b,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
Or35a,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.373832,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
Or42a,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
Or42b,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
Or45a,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
Or45b,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
Or47a,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
Or59a,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.700935,0.0,0.0,0.0,0.0
Or67b,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.448598,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
Or74a,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
Or82a,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
Or85c,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
Or94a,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.873832,0.0,0.0,0.0,0.0
Or94b,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

In [17]:
adult_chem2or.to_csv('data/Dweck2018/adult_chem2glom.csv')
larva_chem2or.to_csv('data/Dweck2018/larva_chem2or.csv')

### supp3 chemical-fruit
Table S2. List of identified active compounds in 34 fruit headspaces (related to Fig. 4)  
Numbers represent normalized relative abundance of the active compounds in each tested fruit extract. In those columns, where no compound reaches the value 1, the compound with highest abundance was not physiologically active

In [18]:
chem2fruit = pd.read_excel('data/Dweck2018/1-s2.0-S2211124718306636-mmc3.xlsx', skiprows=3)
chem2fruit

,Unnamed: 0,CAS number,Apple,Apricot,Avocado,Banana,Blackberry,Blueberry,Cactus fig,Currant,...,Pear,Physalisus,Pineapple,Plums,Pomegranate,Raspberry,Strawberry,Java plum,Af. breadfruit,Watermelon
0,(-)-(E)-Caryophyllene,87-44-5,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.053104,NaN,0.003376,0.482631,0.011736,NaN,0.017498,NaN,0.001189
1,(-)-a-Copaene,3856-25-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(-)-Camphor,464-48-2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.02028,...,0.000259,NaN,NaN,NaN,0.003417,0.003485,0.000310,0.002204,0.019367,0.002581
3,(-)-Menthone,14073-97-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.401326,NaN
4,(-)-Terpinen-4-ol,20126-76-5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.111157,NaN,NaN,NaN,NaN,NaN,0.173440,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,Veratrole,91-16-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.003143,NaN,NaN,NaN,NaN,NaN,0.002965,NaN
112,β-Citronellol,106-22-9,0.000745,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,β-Elemene,33880-83-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.019637,NaN,NaN,NaN,0.001705,NaN,NaN,NaN,0.037121
114,β-Ionone,79-77-6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.628531,NaN,NaN,NaN,NaN
115,β-Myrcene,123-35-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.190336,NaN,NaN,NaN,NaN,0.012457,NaN,NaN,NaN

### supp4: fruit-OR
Table S3. List of fruit-specific activity of all measured responses of neurons expressing larval or adult olfactory receptors (related to Fig. 4)
Total number of responses of individual larval and adult receptors when tested with the individual  fruit headspaces.

In [19]:
supp4 = pd.read_excel(
    'data/Dweck2018/1-s2.0-S2211124718306636-mmc4.xlsx', skiprows=3)
supp4

,Unnamed: 0,Unnamed: 1,Or2a,Or7a,Or13a,Or22c,Or24a,Or30a,Or33b,Or35a,...,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49
0,NaN,African mango,0,1,2,4,1,1,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,African breadfruit,0,4,5,3,1,1,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,African nutmeg,0,1,1,2,1,1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Apple,0,5,2,3,1,1,0,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Apricot,0,0,1,1,1,1,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,NaN,Plums,0,0,2,0,1,2,1,0,...,0,0,0,0,0,0,0,0,0,0
71,NaN,Pomegranate,0,0,1,0,2,1,1,0,...,0,0,0,0,0,0,0,0,0,0
72,NaN,Raspberry,0,2,2,0,2,4,4,0,...,0,0,0,0,0,0,0,0,0,0
73,NaN,Strawberry,0,1,2,0,1,1,8,0,...,0,0,0,0,0,0,0,0,0,0
74,NaN,Watermelon,0,2,1,0,1,3,1,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
larva_fruit2or = supp4.iloc[:34, 1:23]
# based on receptor2glom, I'll take column 'Or42b/ab1' to mean 'either Or42b or sensillum ab1' 
# and approximate it with Or42b
larva_fruit2or.rename(columns={'Unnamed: 1': 'fruit', 'Or42b/ab1': 'Or42b'}, inplace=True)
larva_fruit2or.columns

Index(['fruit', 'Or2a', 'Or7a', 'Or13a', 'Or22c', 'Or24a', 'Or30a', 'Or33b',
       'Or35a', 'Or42a', 'Or42b', 'Or45a', 'Or45b', 'Or47a', 'Or49a', 'Or59a',
       'Or67b', 'Or74a', 'Or82a', 'Or85c', 'Or94a', 'Or94b'],
      dtype='object')

In [21]:
larva_fruit2or = larva_fruit2or.set_index("fruit").T
larva_fruit2or.index.name = "receptor"
larva_fruit2or

fruit,African mango,African breadfruit,African nutmeg,Apple,Apricot,Avocado,Banana,Blackberry,Blueberry,Cactus fig,...,Passionfruit,Peach,Pear,Physalis,Pineapple,Plums,Pomegranate,Raspberry,Strawberry,Watermelon
receptor,,,,,,,,,,,,,,,,,,,,,
Or2a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Or7a,1,4,1,5,0,0,1,0,1,1,...,0,2,5,1,0,0,0,2,1,2
Or13a,2,5,1,2,1,1,2,3,1,2,...,3,2,3,2,2,1,2,2,1,1
Or22c,4,3,2,3,1,0,1,2,0,2,...,5,0,2,3,3,1,0,1,4,2
Or24a,1,1,1,1,1,1,1,0,0,1,...,1,1,1,2,1,1,1,1,1,1
Or30a,1,1,1,1,1,1,1,1,0,0,...,1,1,1,0,1,1,1,1,1,1
Or33b,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Or35a,1,2,0,8,2,1,4,1,1,3,...,0,2,3,3,0,3,0,2,5,2
Or42a,1,4,4,4,2,0,2,0,0,1,...,5,1,3,3,3,0,1,1,3,1
Or42b,1,1,0,1,1,0,1,1,1,1,...,0,1,1,1,1,1,0,1,1,0
Or45a,7,17,5,12,4,0,15,1,1,7,...,22,11,9,14,14,9,0,10,12,6
Or45b,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
Or47a,1,4,0,0,0,0,1,1,0,0,...,1,3,2,1,2,0,0,2,3,0
Or49a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Or59a,3,3,3,2,0,0,4,1,0,3,...,2,0,2,2,3,0,1,1,2,1
Or67b,2,2,1,2,0,0,2,1,1,1,...,3,0,2,1,2,1,0,1,2,1
Or74a,0,6,3,0,0,6,0,0,0,5,...,6,6,12,7,7,8,0,3,3,5
Or82a,1,3,1,1,1,0,0,1,0,2,...,2,1,1,1,2,1,1,1,1,1
Or85c,2,5,1,6,2,0,3,3,1,3,...,7,4,3,3,5,1,1,3,4,2
Or94a,1,2,1,2,2,0,1,2,0,1,...,0,0,0,1,2,0,0,0,1,0
Or94b,1,2,0,0,0,0,1,0,0,0,...,0,0,0,0,3,0,0,0,0,1

In [22]:
adult_fruit2or = supp4.iloc[40:, 1:].reset_index(drop='index')
adult_fruit2or.columns = adult_fruit2or.loc[0]
adult_fruit2or.rename(columns={np.nan: 'fruit'}, inplace=True)
adult_fruit2or = adult_fruit2or.iloc[1:,:]

# some columns are filled with 0s 
# I assume this means that the authors tested these receptors, but they didn't activate in response to fruits 
# so they still contain information, and are to be kept. 

adult_fruit2or.columns

Index(['fruit', 'Or2a', 'Or7a', 'Or9a', 'Or10a', 'Or13a', 'Or19a',
       'Or22a/Or22b', 'Or23a', 'Or33c/Or85e', 'Or35a', 'Or42a', 'Or42b',
       'Or43a', 'Or43b', 'Or46a', 'Or47a', 'Or47b', 'Or49a/Or85f', 'Or49b',
       'Or56a', 'Or59b', 'Or59c', 'Or65a', 'Or67a', 'Or67b', 'Or67c', 'Or67d',
       'Or69a', 'Or71a', 'Or82a', 'Or83c', 'Or85a', 'Or85b', 'Or85d', 'Or88a',
       'Or92a', 'Or98a', 'Gr63a/Gr21a', 'Ir31a', 'Ir41a/Ir76b', 'Ir75a',
       'Ir75c/Ir75b/Ir75a', 'Ir75d', 'Ir75d', 'Ir75d', 'Ir76a/Ir76b', 'Ir84a',
       'Ir92a/Ir76b'],
      dtype='object', name=0)

In [23]:
colsums = adult_fruit2or.sum()
colsums[colsums == 0].index

Index(['Or2a', 'Or23a', 'Or43a', 'Or47b', 'Or49a/Or85f', 'Or56a', 'Or65a',
       'Or67d', 'Or88a', 'Gr63a/Gr21a', 'Ir31a', 'Ir41a/Ir76b', 'Ir75a',
       'Ir75c/Ir75b/Ir75a', 'Ir75d', 'Ir75d', 'Ir75d', 'Ir76a/Ir76b', 'Ir84a',
       'Ir92a/Ir76b'],
      dtype='object', name=0)

In [24]:
adult_fruit2or = adult_fruit2or.loc[:, ~
                                    adult_fruit2or.columns.duplicated()].copy()
# duplicate columns with multiple receptors 
adult_fruit2or.loc[:,['Or22b']] = adult_fruit2or['Or22a/Or22b']
adult_fruit2or.loc[:, ['Or85e']] = adult_fruit2or['Or33c/Or85e'].copy()
adult_fruit2or.rename(columns = {
    'Or22a/Or22b': 'Or22a', 
    'Or33c/Or85e': 'Or33c'
}, inplace = True)
# after manual checking, all other columns with '/' all have 0s in all the constituents 
adult_fruit2or.loc[:, ['Or49a', 'Or85f', 'Gr63a',
                       'Gr21a', 'Ir41a', 'Ir76b', 'Ir75c', 'Ir75b', 'Ir76a', 'Ir92a']] = 0
adult_fruit2or.drop(['Or49a/Or85f','Gr63a/Gr21a', 'Ir41a/Ir76b', 'Ir75c/Ir75b/Ir75a', 'Ir76a/Ir76b', 'Ir92a/Ir76b'], axis = 1, inplace = True)

# and transpose
adult_fruit2or = adult_fruit2or.set_index('fruit').T
adult_fruit2or.index.name = 'receptor'
adult_fruit2or

fruit,African breadfruit,African mango,African nutmeg,Apple,Apricot,Avocado,Banana,Blackberry,Blueberry,Cactus fig,...,Passionfruit,Peach,Pear,Physalis,Pineapple,Plums,Pomegranate,Raspberry,Strawberry,Watermelon
receptor,,,,,,,,,,,,,,,,,,,,,
Or2a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Or7a,4,1,1,5,0,0,1,0,1,1,...,0,2,5,1,0,0,0,2,1,2
Or9a,2,2,1,1,1,0,3,1,2,3,...,4,1,1,3,3,2,1,2,2,1
Or10a,0,4,3,0,1,0,0,0,0,1,...,3,0,0,2,1,0,0,0,0,0
Or13a,5,2,1,2,1,1,2,3,1,2,...,3,2,3,2,2,1,2,2,1,1
Or19a,4,5,12,1,0,3,2,0,0,0,...,6,0,1,6,0,2,1,4,1,3
Or22a,11,8,4,9,1,1,3,7,4,8,...,5,4,4,5,8,1,1,4,8,1
Or23a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Or33c,3,2,6,2,2,0,0,0,0,0,...,5,3,0,5,2,0,0,5,2,2
Or35a,2,1,0,8,2,1,4,1,1,3,...,0,2,3,3,0,3,0,2,5,2
Or42a,4,1,4,4,2,0,2,0,0,1,...,5,1,3,3,3,0,1,1,3,1
Or42b,1,1,0,1,1,0,1,1,1,1,...,0,1,1,1,1,1,0,1,1,0
Or43a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Or43b,2,9,2,6,1,0,5,1,1,2,...,8,2,4,5,11,4,1,0,8,0
Or46a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
Or47a,4,1,0,0,0,0,1,1,0,0,...,1,3,2,1,2,0,0,2,3,0
Or47b,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Or49b,1,0,1,0,0,0,1,0,1,1,...,0,0,0,0,2,0,0,0,0,0
Or56a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Or59b,2,0,0,0,2,0,0,1,0,0,...,0,1,1,0,2,0,0,3,3,0
Or59c,2,2,2,6,2,2,4,1,2,4,...,3,4,3,2,1,2,2,2,3,2
Or65a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Or67a,15,16,6,24,9,0,14,2,1,10,...,16,1,8,10,13,5,0,2,11,1
Or67b,2,2,1,2,0,0,2,1,1,1,...,3,0,2,1,2,1,0,1,2,1
Or67c,1,1,0,1,1,0,1,1,1,0,...,0,1,1,1,1,1,0,1,1,1
Or67d,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Or69a,0,0,2,3,0,0,1,0,0,0,...,9,4,2,1,4,3,0,0,4,1
Or71a,6,2,0,0,0,0,1,0,0,1,...,2,0,1,1,2,0,0,0,1,0
Or82a,3,1,1,1,1,0,0,1,0,2,...,2,1,1,1,2,1,1,1,1,1
Or83c,0,0,0,2,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
Or85a,3,2,0,3,0,0,2,1,0,1,...,6,0,1,5,2,0,0,1,3,0
Or85b,3,2,1,5,3,0,5,2,1,4,...,6,1,2,2,1,2,0,1,3,1
Or85d,2,1,1,2,1,1,2,1,1,2,...,4,4,3,1,4,1,1,1,1,1
Or88a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Or92a,0,0,0,1,1,0,1,0,0,1,...,0,1,0,0,1,1,1,1,1,1
Or98a,10,4,4,9,2,0,2,1,1,1,...,9,2,10,5,7,2,1,3,4,2
Ir31a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ir75a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ir75d,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ir84a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Or22b,11,8,4,9,1,1,3,7,4,8,...,5,4,4,5,8,1,1,4,8,1
Or85e,3,2,6,2,2,0,0,0,0,0,...,5,3,0,5,2,0,0,5,2,2
Or49a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Or85f,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Gr63a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Gr21a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ir41a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ir76b,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ir75c,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ir75b,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ir76a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ir92a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [25]:
# try to map to glomeruli
adult_fruit2or.index.map(receptor_to_glom)

Index([  'DA4m',    'DL5',    'VM3',    'DL1',    'DC2',    'DC1',    'DM2',
          'DA3',    'VC1',    'VC3',   'VM7d',    'DM1',   'DA4l',    'VM2',
         'VA7l',    'DM3',   'VA1v',    'VA5',    'DA2',    'DM4',   'VM7v',
          'DL3',    'DM6',    'VA3',    'VC4',    'DA1',      'D',    'VC2',
          'VA6',    'DC3',    'DM5',   'VM5d',    'VA4',   'VA1d',    'VA2',
         'VM5v',   'VL2p',   'DP1l',    'VL1',   'VL2a',    'DM2',    'VC1',
          'DL4',    'DL4',      nan,      nan,    'VC5',      nan, 'DL2d/v',
       'DL2d/v',    'VM4',    'VM1'],
      dtype='object', name='receptor')

In [26]:
# which receptors are not mapped to a glomerulus?
adult_fruit2or.index[~adult_fruit2or.index.isin(receptor_to_glom)]

Index(['Gr63a', 'Gr21a', 'Ir76b'], dtype='object', name='receptor')

In [27]:
adult_fruit2or.loc['Ir76b',:].sum()

0

Gr63a and Gr21a are shwon to innervate glomerulus V in [Kwon et al. 2007](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1805529/). Ir76b innervates multiple glomeruli [Task et al. 2022](https://elifesciences.org/articles/72599) (table 3), but the values are all 0 here. So let's ignore.

In [28]:
receptor_to_glom.update({'Gr63a':'V', 'Gr21a':'V'})
adult_fruit2or.index = adult_fruit2or.index.map(receptor_to_glom)
adult_fruit2or.index.name = 'glomerulus'
adult_fruit2or

fruit,African breadfruit,African mango,African nutmeg,Apple,Apricot,Avocado,Banana,Blackberry,Blueberry,Cactus fig,...,Passionfruit,Peach,Pear,Physalis,Pineapple,Plums,Pomegranate,Raspberry,Strawberry,Watermelon
glomerulus,,,,,,,,,,,,,,,,,,,,,
DA4m,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DL5,4,1,1,5,0,0,1,0,1,1,...,0,2,5,1,0,0,0,2,1,2
VM3,2,2,1,1,1,0,3,1,2,3,...,4,1,1,3,3,2,1,2,2,1
DL1,0,4,3,0,1,0,0,0,0,1,...,3,0,0,2,1,0,0,0,0,0
DC2,5,2,1,2,1,1,2,3,1,2,...,3,2,3,2,2,1,2,2,1,1
DC1,4,5,12,1,0,3,2,0,0,0,...,6,0,1,6,0,2,1,4,1,3
DM2,11,8,4,9,1,1,3,7,4,8,...,5,4,4,5,8,1,1,4,8,1
DA3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VC1,3,2,6,2,2,0,0,0,0,0,...,5,3,0,5,2,0,0,5,2,2
VC3,2,1,0,8,2,1,4,1,1,3,...,0,2,3,3,0,3,0,2,5,2
VM7d,4,1,4,4,2,0,2,0,0,1,...,5,1,3,3,3,0,1,1,3,1
DM1,1,1,0,1,1,0,1,1,1,1,...,0,1,1,1,1,1,0,1,1,0
DA4l,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VM2,2,9,2,6,1,0,5,1,1,2,...,8,2,4,5,11,4,1,0,8,0
VA7l,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
DM3,4,1,0,0,0,0,1,1,0,0,...,1,3,2,1,2,0,0,2,3,0
VA1v,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VA5,1,0,1,0,0,0,1,0,1,1,...,0,0,0,0,2,0,0,0,0,0
DA2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DM4,2,0,0,0,2,0,0,1,0,0,...,0,1,1,0,2,0,0,3,3,0
VM7v,2,2,2,6,2,2,4,1,2,4,...,3,4,3,2,1,2,2,2,3,2
DL3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DM6,15,16,6,24,9,0,14,2,1,10,...,16,1,8,10,13,5,0,2,11,1
VA3,2,2,1,2,0,0,2,1,1,1,...,3,0,2,1,2,1,0,1,2,1
VC4,1,1,0,1,1,0,1,1,1,0,...,0,1,1,1,1,1,0,1,1,1
DA1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
D,0,0,2,3,0,0,1,0,0,0,...,9,4,2,1,4,3,0,0,4,1
VC2,6,2,0,0,0,0,1,0,0,1,...,2,0,1,1,2,0,0,0,1,0
VA6,3,1,1,1,1,0,0,1,0,2,...,2,1,1,1,2,1,1,1,1,1
DC3,0,0,0,2,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
DM5,3,2,0,3,0,0,2,1,0,1,...,6,0,1,5,2,0,0,1,3,0
VM5d,3,2,1,5,3,0,5,2,1,4,...,6,1,2,2,1,2,0,1,3,1
VA4,2,1,1,2,1,1,2,1,1,2,...,4,4,3,1,4,1,1,1,1,1
VA1d,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VA2,0,0,0,1,1,0,1,0,0,1,...,0,1,0,0,1,1,1,1,1,1
VM5v,10,4,4,9,2,0,2,1,1,1,...,9,2,10,5,7,2,1,3,4,2
VL2p,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DP1l,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VL1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VL2a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DM2,11,8,4,9,1,1,3,7,4,8,...,5,4,4,5,8,1,1,4,8,1
VC1,3,2,6,2,2,0,0,0,0,0,...,5,3,0,5,2,0,0,5,2,2
DL4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DL4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
V,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
V,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VC5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
NaN,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DL2d/v,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DL2d/v,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VM4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VM1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [29]:
# multiple receptors are mapped to the same glomerulus. In this case we take the max:
# if any receptor activates, the glomerulus is activated.
adult_fruit2or = adult_fruit2or.groupby('glomerulus').max()
# now split 'DL2d/v' into 'DL2d' and 'DL2v'
adult_fruit2or.loc['DL2d',:] = adult_fruit2or.loc['DL2d/v', :].copy()
adult_fruit2or.rename(index={'DL2d/v': 'DL2v'}, inplace=True)

adult_fruit2or 
# note how now the 'NaN' row is gone (compared to the last code block) - probably because of the grouping by function

fruit,African breadfruit,African mango,African nutmeg,Apple,Apricot,Avocado,Banana,Blackberry,Blueberry,Cactus fig,...,Passionfruit,Peach,Pear,Physalis,Pineapple,Plums,Pomegranate,Raspberry,Strawberry,Watermelon
glomerulus,,,,,,,,,,,,,,,,,,,,,
D,0,0,2,3,0,0,1,0,0,0,...,9,4,2,1,4,3,0,0,4,1
DA1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DA2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DA3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DA4l,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DA4m,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DC1,4,5,12,1,0,3,2,0,0,0,...,6,0,1,6,0,2,1,4,1,3
DC2,5,2,1,2,1,1,2,3,1,2,...,3,2,3,2,2,1,2,2,1,1
DC3,0,0,0,2,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
DL1,0,4,3,0,1,0,0,0,0,1,...,3,0,0,2,1,0,0,0,0,0
DL2v,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DL3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DL4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
DL5,4,1,1,5,0,0,1,0,1,1,...,0,2,5,1,0,0,0,2,1,2
DM1,1,1,0,1,1,0,1,1,1,1,...,0,1,1,1,1,1,0,1,1,0
DM2,11,8,4,9,1,1,3,7,4,8,...,5,4,4,5,8,1,1,4,8,1
DM3,4,1,0,0,0,0,1,1,0,0,...,1,3,2,1,2,0,0,2,3,0
DM4,2,0,0,0,2,0,0,1,0,0,...,0,1,1,0,2,0,0,3,3,0
DM5,3,2,0,3,0,0,2,1,0,1,...,6,0,1,5,2,0,0,1,3,0
DM6,15,16,6,24,9,0,14,2,1,10,...,16,1,8,10,13,5,0,2,11,1
DP1l,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
V,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VA1d,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VA1v,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VA2,0,0,0,1,1,0,1,0,0,1,...,0,1,0,0,1,1,1,1,1,1
VA3,2,2,1,2,0,0,2,1,1,1,...,3,0,2,1,2,1,0,1,2,1
VA4,2,1,1,2,1,1,2,1,1,2,...,4,4,3,1,4,1,1,1,1,1
VA5,1,0,1,0,0,0,1,0,1,1,...,0,0,0,0,2,0,0,0,0,0
VA6,3,1,1,1,1,0,0,1,0,2,...,2,1,1,1,2,1,1,1,1,1
VA7l,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
VC1,3,2,6,2,2,0,0,0,0,0,...,5,3,0,5,2,0,0,5,2,2
VC2,6,2,0,0,0,0,1,0,0,1,...,2,0,1,1,2,0,0,0,1,0
VC3,2,1,0,8,2,1,4,1,1,3,...,0,2,3,3,0,3,0,2,5,2
VC4,1,1,0,1,1,0,1,1,1,0,...,0,1,1,1,1,1,0,1,1,1
VC5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VL1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VL2a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VL2p,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VM1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VM2,2,9,2,6,1,0,5,1,1,2,...,8,2,4,5,11,4,1,0,8,0
VM3,2,2,1,1,1,0,3,1,2,3,...,4,1,1,3,3,2,1,2,2,1
VM4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VM5d,3,2,1,5,3,0,5,2,1,4,...,6,1,2,2,1,2,0,1,3,1
VM5v,10,4,4,9,2,0,2,1,1,1,...,9,2,10,5,7,2,1,3,4,2
VM7d,4,1,4,4,2,0,2,0,0,1,...,5,1,3,3,3,0,1,1,3,1
VM7v,2,2,2,6,2,2,4,1,2,4,...,3,4,3,2,1,2,2,2,3,2
DL2d,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [30]:
adult_fruit2or.to_csv('data/Dweck2018/adult_fruit2glom.csv')
larva_fruit2or.to_csv('data/Dweck2018/larva_fruit2or.csv')