In [1]:
import pandas as pd

In [2]:
exdata = pd.read_csv('data/Liu2022/Liu2022_tableS3.csv')
neuronmeta = pd.read_csv('data/Liu2022/Liu2022_tableS1.csv')
exdata

,Connection,mean # of synapses,LHN surface area (μm2),mean synapse density (μm-2),mean EPSP amplitude (mV)
0,DA4l/L1',0.000000,1493.5,0.0000,0.000000
1,DC1/L1',5.666667,1493.5,0.0038,NaN
2,DL4/L1',0.000000,1493.5,0.0000,0.000000
3,DL5/L1',0.000000,1493.5,0.0000,0.842270
4,DM1/L1',9.000000,1493.5,0.0060,1.616176
...,...,...,...,...,...
151,VA2/L13',9.000000,1710.7,0.0053,1.402496
152,VA6/L13',0.000000,1710.7,0.0000,0.000000
153,VC1/L13',0.000000,1710.7,0.0000,0.000000
154,VL2a/L13',0.000000,1710.7,0.0000,0.000000
155,VL2p/L13',0.000000,1710.7,0.0000,0.000000

In [3]:
neuronmeta

,Cell class,Cell type name (Jeanne 2018 nomenclature for LHNs),hemibrain body ID,hemibrain type,Nblast Score (avg) LHNs only,NBlast Rank (x/1496) LHNs only
0,PN,DA4l,544021095,DA4l,NaN,NaN
1,PN,DC1,1640594274,DC1,NaN,NaN
2,PN,DL4,1670934213,DL4,NaN,NaN
3,PN,DL5,693483018,DL5,NaN,NaN
4,PN,DM1,542634818,DM1,NaN,NaN
...,...,...,...,...,...,...
61,LHN,V2,851961337,LHAV2b2_a,0.439503,9.0
62,LHN,V3,915724147,LHAV1a2_b,0.519238,1.0
63,LHN,V3,883338122,LHAV1a1,0.491281,2.0
64,LHN,V3,789588935,LHAV1a1,0.429195,5.0
65,LHN,V3,917450071,LHAV1a2_a,0.422676,8.0

In [4]:
neuronmeta[neuronmeta["hemibrain type"].str.contains("LHAV6a3")]

,Cell class,Cell type name (Jeanne 2018 nomenclature for LHNs),hemibrain body ID,hemibrain type,Nblast Score (avg) LHNs only,NBlast Rank (x/1496) LHNs only
15,LHN,L11,329211098,LHAV6a3_a,0.554796,1.0
16,LHN,L11,297921527,LHAV6a3_a,0.526498,5.0
17,LHN,L11,360578457,LHAV6a3_a,0.524718,7.0
22,LHN,L12,421957711,LHAV6a3_b,0.504550,6.0
24,LHN,L12,603681826,LHAV6a3_b,0.479775,10.0
25,LHN,L12,391609333,LHAV6a3_b,0.470003,13.0

In [5]:
exdata[exdata.Connection.str.contains("DM4/L11|DM4/L12")]

,Connection,mean # of synapses,LHN surface area (μm2),mean synapse density (μm-2),mean EPSP amplitude (mV)
17,DM4/L11',1.0,2063.2,0.0005,0.0
29,DM4/L12',6.6,1848.6,0.0036,0.0

In [6]:
# modify cell types for flywire types
neuronmeta['flywire_type'] = neuronmeta['hemibrain type'].replace(
    {
        "LHAV6a3_a": "LHAV6a3",
        "LHAV6a3_b": "LHAV6a3",
        "LHAV6a1_b": "LHAV6a1",
        "LHPV5c1_d": "LHPV5c1",
        "LHAD1b2_c": "LHAD1b2_a,LHAD1b2_c",
        "LHAD1b2_a": "LHAD1b2_a,LHAD1b2_c",
        "LHAV2b2_b": "LHAV2b2b",
        "LHAV2b2_a": "LHAV2b2a",
    },
    
)
# LHAV6a2, LHPD3a1, LHAD1b2_b, LHPD2b1_a, LHPD2b1_b, LHPD2a1, LHAV1a2_b, LHAV1a2_a don't exist in FAFB
jeannetype_to_hemibrain_type = dict(
    zip(
        neuronmeta["Cell type name (Jeanne 2018 nomenclature for LHNs)"],
        neuronmeta["hemibrain type"],
    )
)
jeannetype_to_fafb_type = dict(
    zip(
        neuronmeta["Cell type name (Jeanne 2018 nomenclature for LHNs)"],
        neuronmeta["flywire_type"],
    )
)

In [7]:
exdata.loc[:, ["pre"]] = exdata.Connection.str.split("/").str[0]
exdata.loc[:, ["post"]] = exdata.Connection.str.split("/").str[1]
exdata.post = exdata.post.str.replace("'", '')
exdata

,Connection,mean # of synapses,LHN surface area (μm2),mean synapse density (μm-2),mean EPSP amplitude (mV),pre,post
0,DA4l/L1',0.000000,1493.5,0.0000,0.000000,DA4l,L1
1,DC1/L1',5.666667,1493.5,0.0038,NaN,DC1,L1
2,DL4/L1',0.000000,1493.5,0.0000,0.000000,DL4,L1
3,DL5/L1',0.000000,1493.5,0.0000,0.842270,DL5,L1
4,DM1/L1',9.000000,1493.5,0.0060,1.616176,DM1,L1
...,...,...,...,...,...,...,...
151,VA2/L13',9.000000,1710.7,0.0053,1.402496,VA2,L13
152,VA6/L13',0.000000,1710.7,0.0000,0.000000,VA6,L13
153,VC1/L13',0.000000,1710.7,0.0000,0.000000,VC1,L13
154,VL2a/L13',0.000000,1710.7,0.0000,0.000000,VL2a,L13
155,VL2p/L13',0.000000,1710.7,0.0000,0.000000,VL2p,L13

In [8]:
exdata.loc[:, ['pre_type']] = exdata.pre + '_adPN'
exdata.loc[exdata.pre.isin(["DM1", "VC1"]), 'pre_type'] = exdata[exdata.pre.isin(["DM1", "VC1"])].pre + '_lPN'
exdata

,Connection,mean # of synapses,LHN surface area (μm2),mean synapse density (μm-2),mean EPSP amplitude (mV),pre,post,pre_type
0,DA4l/L1',0.000000,1493.5,0.0000,0.000000,DA4l,L1,DA4l_adPN
1,DC1/L1',5.666667,1493.5,0.0038,NaN,DC1,L1,DC1_adPN
2,DL4/L1',0.000000,1493.5,0.0000,0.000000,DL4,L1,DL4_adPN
3,DL5/L1',0.000000,1493.5,0.0000,0.842270,DL5,L1,DL5_adPN
4,DM1/L1',9.000000,1493.5,0.0060,1.616176,DM1,L1,DM1_lPN
...,...,...,...,...,...,...,...,...
151,VA2/L13',9.000000,1710.7,0.0053,1.402496,VA2,L13,VA2_adPN
152,VA6/L13',0.000000,1710.7,0.0000,0.000000,VA6,L13,VA6_adPN
153,VC1/L13',0.000000,1710.7,0.0000,0.000000,VC1,L13,VC1_lPN
154,VL2a/L13',0.000000,1710.7,0.0000,0.000000,VL2a,L13,VL2a_adPN
155,VL2p/L13',0.000000,1710.7,0.0000,0.000000,VL2p,L13,VL2p_adPN

In [9]:
exdata.loc[:, ["post_hemibrain_type"]] = exdata.post.map(jeannetype_to_hemibrain_type)
exdata.loc[:, ["post_fafb_type"]] = exdata.post.map(jeannetype_to_fafb_type)
exdata

,Connection,mean # of synapses,LHN surface area (μm2),mean synapse density (μm-2),mean EPSP amplitude (mV),pre,post,pre_type,post_hemibrain_type,post_fafb_type
0,DA4l/L1',0.000000,1493.5,0.0000,0.000000,DA4l,L1,DA4l_adPN,LHAD1a1,LHAD1a1
1,DC1/L1',5.666667,1493.5,0.0038,NaN,DC1,L1,DC1_adPN,LHAD1a1,LHAD1a1
2,DL4/L1',0.000000,1493.5,0.0000,0.000000,DL4,L1,DL4_adPN,LHAD1a1,LHAD1a1
3,DL5/L1',0.000000,1493.5,0.0000,0.842270,DL5,L1,DL5_adPN,LHAD1a1,LHAD1a1
4,DM1/L1',9.000000,1493.5,0.0060,1.616176,DM1,L1,DM1_lPN,LHAD1a1,LHAD1a1
...,...,...,...,...,...,...,...,...,...,...
151,VA2/L13',9.000000,1710.7,0.0053,1.402496,VA2,L13,VA2_adPN,LHAV6a2_b,LHAV6a2_b
152,VA6/L13',0.000000,1710.7,0.0000,0.000000,VA6,L13,VA6_adPN,LHAV6a2_b,LHAV6a2_b
153,VC1/L13',0.000000,1710.7,0.0000,0.000000,VC1,L13,VC1_lPN,LHAV6a2_b,LHAV6a2_b
154,VL2a/L13',0.000000,1710.7,0.0000,0.000000,VL2a,L13,VL2a_adPN,LHAV6a2_b,LHAV6a2_b
155,VL2p/L13',0.000000,1710.7,0.0000,0.000000,VL2p,L13,VL2p_adPN,LHAV6a2_b,LHAV6a2_b

In [10]:
exdata = exdata.loc[
    exdata["mean EPSP amplitude (mV)"].notna(),
    ["pre_type", "post_hemibrain_type", 'post_fafb_type', "mean EPSP amplitude (mV)"],
]
exdata.rename(columns={"mean EPSP amplitude (mV)": "mean_EPSP_amplitude"}, inplace=True)
exdata.to_csv('data/Liu2022/data_tidy.csv', index=False)